### ISSUE TITLE
Disproportionately high iVeg numbers in BRAT Table 

### ISSUE THREAD

**Issue by kbartelt** [Riverscapes/pyBRAT#140] opened 2018-08-07 22:58 UTC
Hi @banderson1618 

Can you take a look at my BRAT Table and output for the Middle Owyhee ( #136 )? I noticed a few areas with some unusually high vegetation and dam capacity outputs in areas with a VEG_CODE input of 1 and 2.

![image](https://user-images.githubusercontent.com/39836333/43806349-d6436a3c-9a60-11e8-864d-b108b92d50ee.png)

![image](https://user-images.githubusercontent.com/39836333/43806394-fe90e104-9a60-11e8-8579-addd536fba05.png)

![image](https://user-images.githubusercontent.com/39836333/43806452-3f781c1e-9a61-11e8-8bf5-0f35d2591910.png)

If you look in the circled area in the first photo above there are a few instances of this. Thanks for the help! 

All of my BRAT inputs/ outputs/ a final layer package are located [here.](https://usu.box.com/s/o1e1u37smwy7q1ui8kc0krh904p24rkx)

**Comment by bangen** [comment] 2018-08-08 16:10
@kbartelt I'll take a look at this and get back.

**Comment by bangen** [comment] 2018-08-08 16:16
@kbartelt Quick question.  Did you select the option to in the BRAT Table tool to segment by roads?

**Comment by banderson1618** [comment] 2018-08-08 19:00
I've been looking into this more, and... I still have no idea what the problem is. I can't find any good patterns for what areas get clearly wrong values, and those areas still get way too high values if I set it to take the minimum instead of the mean veg code. The problem pops up throughout the entire watershed, but somehow we've never seen it before in any other watersheds. For some reason, not a single reach has a value below 1, even though 0 is a possible value in the raster.

I'm honestly baffled. This doesn't make sense to me. I'm gonna take a break and look back at this in an hour, because I'm not making progress right now.

**Comment by bangen** [comment] 2018-08-08 20:11
@banderson1618 in case you were looking into this again I wanted to let you know I found the issue.  I'm going to make a video and will post it here.

**Comment by banderson1618** [comment] 2018-08-08 20:17
I'd be very curious to know what the problem was, if nothing else.

**Comment by bangen** [comment] 2018-08-08 20:47
@kbartelt and @banderson1618 

Good news, the issue wasn't with the code itself.  The problem was the 'VEG_CODE' fields were created as text/string fields rather than as integer fields.  You can check out this video [here](https://youtu.be/kz5uha_jbMg) for the in the weeds info.

Karen, you'll need to re-create the 'VEG_CODE' field for the EVT and BPS rasters.  Make sure the field type is set to 'SHORT' (which is type integer).  

I'm going to close this issue for now.  If you re-run and have further issues let us know.

**Closed by bangen** 2018-08-08 20:47 UTC

**Comment by kbartelt** [comment] 2018-08-08 20:52
Ah okay that makes sense. Thank you for the help!!

**Comment by banderson1618** [comment] 2018-08-08 20:55
Good catch, that's a subtle bug!
